export const LOADING_PRODUCT = "LOADING_PRODUCT";
export const GET_PRODUCT_LISTS = "GET_PRODUCT_LISTS";
export const REMOVE_PRODUCT = "REMOVE_PRODUCT";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const GET_DEVICE_OF_SELECTED_PRODUCTID =
  "GET_DEVICE_OF_SELECTED_PRODUCTID";
export const REMOVE_DEVICE = "REMOVE_DEVICE";
export const ADD_DEVICE = "ADD_DEVICE";
export const UPDATE_DEVICE = "UPDATE_DEVICE";
